### ISSUE TITLE
BusyBox 1.24.2

### ISSUE THREAD

**Issue by mfonville** [yashdsaraf/busybox#1]
Apparently the day after making the build, busybox made a new release: http://git.busybox.net/busybox/tree/?h=1_24_stable

I guess we should upgrade to that latest release?

**Comment by yashdsaraf** [comment]
Hey,
As you can see [here](https://git.busybox.net/busybox/log/?h=1_24_stable&showmsg=1) the last commit by mike frysinger is of march 22, and the [log](https://github.com/yashdsaraf/busybox/commits/master) of this repo shows the same commit. I updated the repo as soon as they did, so we're up to date.

**Comment by mfonville** [comment]
Ok :)
