### ISSUE TITLE
BusyBox 1.25.0

### ISSUE THREAD

**Issue by mfonville** [yashdsaraf/busybox#3]
1.25.0 release :-)
https://busybox.net/ (the link in their newsarticle to git is wrong, it is linked to 1_24_stable, it should be https://git.busybox.net/busybox/tree/?h=1_25_stable )

**Comment by yashdsaraf** [comment]
Thanks for the head's up,  I'll be posting updated bins within the hour.

**Comment by yashdsaraf** [comment]
@mfonville The older lzip patch is throwing compiler errors. Looks like we're gonna have to wait for lzip to release an updated patch.

**Comment by mfonville** [comment]
@yashdsaraf ok. Maybe drop a line at their project page?

**Comment by yashdsaraf** [comment]
Looks like we'll get an updated patch soon - http://lists.nongnu.org/archive/html/lzip-bug/2016-06/msg00006.html

**Comment by yashdsaraf** [comment]
Updated busybox with latest lzip patch. Want me to send a pull request of the updated bins when they're done getting tested?
If you'd like to take a look yourself, here's the [link](https://www.androidfilehost.com/?w=files&flid=71927)

**Comment by mfonville** [comment]
Yes, please make a PR if you did test them :)

**Comment by yashdsaraf** [comment]
@mfonville You might wanna see [this](http://lists.nongnu.org/archive/html/lzip-bug/2016-06/msg00007.html), lzip now decompresses at the same speed as xz.

**Comment by mfonville** [comment]
Yes I read. that is good news:)

**Comment by mfonville** [comment]
@yashdsaraf I did do some benchmarking now with the built-in lzip `tar -xyf "$archive.lz"` versus the separate xzdec-binary `xzdec "$archive.xz" | tar -x -f -` and it is still around 24% slower :-/
(but the .lz archives are smaller, so it does compress better! and I understood that lzip has better integrity checking)
Weirdly enough is `lunzip -c "$archive.lz" | tar -x  -f -` only  17% slower :-/

**Comment by mfonville** [comment]
fyi: https://github.com/opengapps/opengapps/commit/441365c085f173885cca713f389c401a2017c726
